markdown: kramdown
highlighter: rouge
theme: jekyll-theme-slate
title: Getting started with Sum of Squares
description: Documentation and examples on using Sum of Squares solvers, tutorial and examples of Sum of Squares programming
google_analytics: UA-43609447-5